### ISSUE TITLE
您好我在运行train.py文件时遇到了如下问题

### ISSUE THREAD

**Issue by Originhhh** [ezeli/BUTD_model#1]
![image](https://user-images.githubusercontent.com/55876617/98889920-d2e83780-24d5-11eb-88af-397f64838ea2.png)

**Comment by ezeli** [comment]
你的h5文件格式对不对？需要先按照 preprocess.py 文件对需要的数据进行处理。

**Comment by Originhhh** [comment]
对的，是按照您那个preprocess文件进行的处理，我觉得问题可能出问题在torch的版本问题，我再试试torch1.2的版本吧，谢谢回复


| |
liuqiong
|
|
15120052980@163.com
|
签名由网易邮箱大师定制
在2020年11月12日 16:04，Li Tong<notifications@github.com> 写道：

你的h5文件格式对不对？需要先按照 preprocess.py 文件对需要的数据进行处理。

**Comment by ezeli** [comment]
看log感觉不太像是torch版本问题，需要确保所有参与训练和验证的图片的特征都提取到h5文件中。项目不局限于MSCOCO数据集，但是你需要将你的数据按照 preprocess.py 文件中 process_coco_captions 函数的数据格式处理好。

**Comment by Originhhh** [comment]
好的，我再试试，如果有问题，再与您联系。非常感谢您的回复


| |
liuqiong
|
|
15120052980@163.com
|
签名由网易邮箱大师定制
在2020年11月12日 16:22，Li Tong<notifications@github.com> 写道：

看log感觉不太像是torch版本问题，需要确保所有参与训练和验证的图片的特征都提取到h5文件中。项目不局限于MSCOCO数据集，但是你需要将你的数据按照 preprocess.py 文件中 process_coco_captions 函数的数据格式处理好。

**Comment by Originhhh** [comment]
您好，我想问一下如果我想尝试其他数据集例如f30k或f8k，是不是需要对 preprocess.py 文件进行一定修改。


| |
liuqiong
|
|
15120052980@163.com
|
签名由网易邮箱大师定制
在2020年11月12日 16:04，Li Tong<notifications@github.com> 写道：

你的h5文件格式对不对？需要先按照 preprocess.py 文件对需要的数据进行处理。

**Comment by ezeli** [comment]
是的，只要保持训练数据的格式一致即可。

**Comment by Originhhh** [comment]
您好，我现在程序已经可以正常运行了，感谢您之前的帮助，然后我想问一下，我要是想要计算bleu4和cider分数我应该如何做呢

**Comment by ezeli** [comment]
可以参考我的另一个仓库：[ezeli/caption_eval](https://github.com/ezeli/caption_eval)

**Comment by Originhhh** [comment]
好的，谢谢，已经可以成功运行。麻烦了
在2020年11月23日 19:50，Li Tong<notifications@github.com> 写道：

可以参考我的另一个仓库：ezeli/caption_eval
