### ISSUE TITLE
FileNotFoundError: model.pth not found.

### ISSUE THREAD

**Issue by yy13138** [ezeli/BUTD_model#14]
Thank you for your contribution, but the model.pth parameter is not disclosed in the project, is there another path to download it?

**Comment by Mahiro2211** [comment]
He gives the link in readme , just watch carefully

**Comment by yy13138** [comment]
Thank you



---Original---
From: "Li ***@***.***&gt;
Date: Tue, Aug 1, 2023 15:04 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ezeli/BUTD_model] FileNotFoundError: model.pth not found. (Issue#14)




 
Closed #14 as completed.

**Comment by yy13138** [comment]
Thank you



---Original---
From: ***@***.***&gt;
Date: Sat, Jul 29, 2023 17:15 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ezeli/BUTD_model] FileNotFoundError: model.pth not found. (Issue#14)




 
He gives the link in readme , just watch carefully
