### ISSUE TITLE
extremly large .h5 file after extracting features with preprocess.py

### ISSUE THREAD

**Issue by 1172100122** [ezeli/BUTD_model#2]
I used preprocess.py to extract feature from COCO2014 dataset, it turns out that the .h5 files are extremely large compared to those pretrained features in https://github.com/peteanderson80/bottom-up-attention

我使用preprocess.py从COCO2014数据集中提取特征，结果得到了远超预期大小的.h5 feature 文件：

(base) [ features]$ ls
coco_att.h5  coco_fc.h5
(base) [ features]$ ls -hl
total 186G
-rw-rw-r-- 1   185G Nov 22 10:40 coco_att.h5
-rw-rw-r-- 1  1013M Nov 22 10:40 coco_fc.h5

这是正常的吗？或者只是因为我无意中同时运行了许多个preprocess进程导致对同一个.h5文件重复写了许多次？
I wonder if it's normal. If not, what might be the cause?
我把COCO train 和 valid 文件都放进了 '../dataset/coco_images/'中，亦即代码中 '--imgs_dir'对应的路径参数
I put both train and valid images in '../dataset/coco_images/',which correspond to '--imgs_dir'

**Comment by ezeli** [comment]
是正常的，preprocess.py文件提取出来的是grid-based features，peteanderson80提供的是region-based features（请查看Readme文件）。将所有的图片（包括训练集、验证集和测试集）放到同一个目录下是正确的，可以查看h5文件，看看是否所有的图片特征都提取好了。

**Comment by PeterBishop0** [comment]
想问一下，preprocess.py好像对于内存要求很大，我16g的RAM跑到一半就内存耗尽，resource限制也没用啊，我该怎么办呢？

**Comment by ezeli** [comment]
我在运行的时候并没有占用很大的内存，并且在运行的时候内存使用量也一直保持平稳，因为程序其实一次只会处理一张图片。我使用的h5py库的版本是2.10.0，你可以检测一下是不是版本问题。

**Comment by PeterBishop0** [comment]
> 我在运行的时候并没有占用很大的内存，并且在运行的时候内存使用量也一直保持平稳，因为程序其实一次只会处理一张图片。我使用的h5py库的版本是2.10.0，你可以检测一下是不是版本问题。

感谢回复！我后来发现test的图片是可以不放进去的，就解决啦，不过提取图片特征的时候也是占了十几个G的内存，就很迷。等训练完我看看版本。
