### ISSUE TITLE
您好麻烦您了！我想实现VQA那个部分

### ISSUE THREAD

**Issue by PeterBishop0** [ezeli/BUTD_model#3]
我想实现VQA那个部分，关于top-down这部分我大概需要改哪些？（大致说说就好了！感谢百忙抽空！）

**Comment by ezeli** [comment]
对于captioning模型来说：每个时间步都需要根据Attention LSTM输出的隐藏状态来对图片区域特征进行注意力加权求和；对于VQA来说：先通过GRU对question进行编码，然后通过编码结果对图片区域特征进行注意力加权求和（只需要一次即可），然后将question编码特征和图片注意力后的特征进行融合，最后计算所有候选答案的得分。主要还是需要参考论文！

**Comment by PeterBishop0** [comment]
好哒！感谢感谢！还是论文没看仔细太菜辣，感谢您抽出时间指导！
