### ISSUE TITLE
FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = './data/features/coco_fc.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

### ISSUE THREAD

**Issue by yangyang32111** [ezeli/BUTD_model#8]
您好，在运行preprocess.py时候出现了如下问题，想请教一下问题出现在哪里？
![Uploading image.png…]()

**Comment by yangyang32111** [comment]
![image](https://user-images.githubusercontent.com/67679842/141883871-e187e639-3d2f-40a2-be45-5644e2abf42a.png)

**Comment by ezeli** [comment]
看一下 h5py 库的版本，我的是 2.10.0，h5py.File 函数的 mode 参数默认是 a，如果不是的话你可以改一下再试试。

**Comment by yangyang32111** [comment]
@ezeli  谢谢回复，已经成功运行了！

**Comment by ZKY1234** [comment]
> @ezeli 谢谢回复，已经成功运行了！

遇到了同样的问题，请教下博主是怎么解决的呢？
