### ISSUE TITLE
Excuse me, what are _fc.h5 and _att.h5 in the file preprocess.py? Where to get it?

### ISSUE THREAD

**Issue by zhuhaifengaaa** [ezeli/BUTD_model#9]
Excuse me, what are _fc.h5 and _att.h5 in the file preprocess.py? Where to get it?
Thank you!

**Comment by ezeli** [comment]
Please read the Readme. _fc.h5 and _att.h5 are generated during preprocessing.

**Comment by zhuhaifengaaa** [comment]
> Please read the Readme. _fc.h5 and _att.h5 are generated during preprocessing.

OK, thank you very much
